/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

export default function Model({ ...props }) {
  const boxSize = [0.1,0.1,0.1];
  const [ref] = useBox(() => ({
    mass: 5, 
    args: boxSize, 
    ...props
  }))
  const group = useRef()
  const { nodes, materials } = useGLTF('/wheelchair.glb')
  return (
    <mesh ref={ref}>
      <group ref={group} {...props} dispose={null}>
        <mesh scale={0.08} geometry={nodes.kurumaisuunity_1.geometry} material={materials.SimplygonMaterial_LOD1} position={[-9.3, -11.6, -9.5]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </mesh>
    
  )
}

useGLTF.preload('/wheelchair.glb')
